# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(10, '1 day'), (30, '7 days')])),
                ('status', models.IntegerField(choices=[(0, 'New'), (10, 'Published (Still can buy a ticket)'), (20, 'Canceled (no winner)'), (30, 'Finished (has winner)')])),
                ('smart_contract_id', models.CharField(max_length=42)),
                ('transaction_id', models.CharField(max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ending_at', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
