# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.IntegerField(choices=[(10, 'IOS'), (20, 'Android OS')])),
                ('token', models.CharField(max_length=1024)),
                ('fail_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('os', 'token')]),
        ),
    ]
