# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170921_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.IntegerField(choices=[(10, '1 day'), (30, '7 days'), (50, '30 days')]),
        ),
    ]
