# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171021_0745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
