# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delete_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Published (Still can buy a ticket)'), (15, 'Winner choosing in progress'), (20, 'Canceled (no winner)'), (30, 'Finished (has winner)')], default=0),
        ),
    ]
