# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171029_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bet_amount',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Published (Still can buy a ticket)'), (15, 'Finishing (Winner choosing in progress)'), (20, 'Canceled (no winner)'), (30, 'Finished (has winner)')], default=0),
        ),
    ]
