# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0005_applicationid'),
        ('backend', '0008_auto_20171103_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('dayly_game_notifications_enabled', models.BooleanField(default=True)),
                ('weekly_game_notifications_enabled', models.BooleanField(default=True)),
                ('bonus_game_notifications_enabled', models.BooleanField(default=True)),
                ('apns_device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_apns_device', to='push_notifications.APNSDevice')),
                ('gcm_device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_gcm_device', to='push_notifications.GCMDevice')),
            ],
        ),
    ]
