# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20171116_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='token_game_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.IntegerField(choices=[(10, '1 day'), (30, '7 days'), (50, '30 days'), (70, 'Token game')]),
        ),
    ]
