# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 15:37
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20180206_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=64, validators=[backend.models.wallet_validation])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='backend.Game')),
            ],
        ),
    ]
