# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 19:19
from __future__ import unicode_literals

from django.db import migrations
from django.apps import apps


def clear_game_players(*args, **kwargs):
    GamePlayer = apps.get_model('backend', 'GamePlayer')

    GamePlayer.objects.all().delete()

def dummy_fn(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_gameplayers'),
    ]

    operations = [
        migrations.RenameModel('GamePlayers', 'GamePlayer'),
        migrations.RunPython(clear_game_players, reverse_code=dummy_fn),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together=set([('game', 'wallet')]),
        ),
    ]
