# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20180214_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='backend.Game'),
        ),
    ]
